//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formulate.Pro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Formulate.Pro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///    &lt;div class=&quot;umb-el-wrap&quot;&gt;
        ///        &lt;label class=&quot;control-label&quot;&gt;
        ///            &lt;localize key=&quot;formulate-labels_Sender Email&quot;&gt;
        ///                Sender Email
        ///            &lt;/localize&gt;
        ///        &lt;/label&gt;
        ///        &lt;div class=&quot;controls controls-row&quot;&gt;
        ///            &lt;div&gt;
        ///                &lt;input class=&quot;formulate__text--wide&quot; type=&quot;text&quot; ng-model=&quot;configuration.senderEmail&quot; /&gt;
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;umb-el-wrap&quot;&gt;
        ///        &lt;label class=&quot;control-label&quot;&gt;
        ///            &lt;l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string designedEmailHandler_html {
            get {
                return ResourceManager.GetString("designedEmailHandler_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Variables.
        ///var app = angular.module(&quot;umbraco&quot;);
        ///
        ///// Associate directive/controller.
        ///app.directive(&quot;formulateDesignedEmailHandler&quot;, directive);
        ///
        ///// Directive.
        ///function directive() {
        ///    return {
        ///        restrict: &quot;E&quot;,
        ///        replace: true,
        ///        templateUrl: &quot;/App_Plugins/Formulate.Pro/Directives/Handlers/DesignedEmailHandler/designedEmailHandler.html&quot;,
        ///        scope: {
        ///            configuration: &quot;=&quot;,
        ///            fields: &quot;=&quot;
        ///        },
        ///        controller: Controller
        ///    };
        ///}
        ///
        ///// Con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string designedEmailHandler_js {
            get {
                return ResourceManager.GetString("designedEmailHandler_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;language alias=&quot;en_us&quot; intName=&quot;English (US)&quot; localName=&quot;English (US)&quot; lcid=&quot;&quot; culture=&quot;en-US&quot;&gt;
        ///  &lt;area alias=&quot;formulate-label-descriptions&quot;&gt;
        ///    &lt;key alias=&quot;Subject Razor Path&quot;&gt;
        ///      Optional. The path to the Razor view that renders the subject line. For example,
        ///      &quot;~\Views\Emails\Contact Us (Subject).cshtml&quot; (without quotes).
        ///    &lt;/key&gt;
        ///    &lt;key alias=&quot;HTML Email Razor Path&quot;&gt;
        ///      Required. The path to the Razor view that renders the H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_GB_xml {
            get {
                return ResourceManager.GetString("en_GB_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;language alias=&quot;en_us&quot; intName=&quot;English (US)&quot; localName=&quot;English (US)&quot; lcid=&quot;&quot; culture=&quot;en-US&quot;&gt;
        ///  &lt;area alias=&quot;formulate-label-descriptions&quot;&gt;
        ///    &lt;key alias=&quot;Subject Razor Path&quot;&gt;
        ///      Optional. The path to the Razor view that renders the subject line. For example,
        ///      &quot;~\Views\Emails\Contact Us (Subject).cshtml&quot; (without quotes).
        ///    &lt;/key&gt;
        ///    &lt;key alias=&quot;HTML Email Razor Path&quot;&gt;
        ///      Required. The path to the Razor view that renders the H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_US_xml {
            get {
                return ResourceManager.GetString("en_US_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Formulate_Pro_Sample__HTML_cshtml {
            get {
                object obj = ResourceManager.GetObject("Formulate_Pro_Sample__HTML_cshtml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Formulate_Pro_Sample__Subject_cshtml {
            get {
                object obj = ResourceManager.GetObject("Formulate_Pro_Sample__Subject_cshtml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Formulate_Pro_Sample__Text_cshtml {
            get {
                object obj = ResourceManager.GetObject("Formulate_Pro_Sample__Text_cshtml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] package_manifest {
            get {
                object obj = ResourceManager.GetObject("package_manifest", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
